### ISSUE TITLE
直接没有过程，提示完成

### ISSUE THREAD

**Issue by toneytang** [hongfs/python-douyin#1]
https://www.iesdouyin.com/share/video/6598037278042361091/?region=NZ&mid=6519411666773117699&u_code=14ml9eejh&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme&iid=43753084644&timestamp=1536531209

试这个链接。直接完成，但没有找到文件存在哪里。而且没有代码中的进度显示。

************************************************************
                抖音无水印视频下载
        作者:hongfs(https://github.com/hongfs)
************************************************************
请输入分享链接：https://www.iesdouyin.com/share/video/6598037278042361091/?region=NZ&mid=6519411666773117699&u_code=14ml9eejh&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme&iid=43753084644&timestamp=1536531209

完成

**Comment by hongfs** [comment]
暂时不会进行维护了。您可以尝试下https://github.com/Jack-Cherish/python-spider 这个
